/**
 * Vehicle icon atlas.
 *
 * Every entry is a `mask` icon: deck.gl takes only the alpha channel and tints it
 * with `getColor`. That has two consequences the previous atlas got wrong, so
 * they are worth stating up front:
 *
 *  1. Dark "window" rectangles do not shade the vehicle, they punch holes in it —
 *     the basemap shows through. Detail must be expressed as *shape*, never as a
 *     dark fill.
 *  2. One draw gives one colour. The body/ring/casing look therefore needs three
 *     passes over three concentric silhouettes.
 *
 * The three silhouettes are generated by stroking the *same* base path with
 * increasing widths (a stroke of width W grows the outline by W/2 on every side),
 * so they stay exactly concentric and their relative thickness is fixed. This
 * replaces the old approach of drawing one shape at 1.18x under a copy at 0.94x,
 * where the "outline" collapsed into a 1px fringe as soon as both hit the
 * min-pixel clamp.
 *
 * Slot rectangles and the SVG are derived from the same constants below. The
 * previous atlas hard-coded both and they disagreed: the bus slot sampled
 * y 0..120 while the bus was drawn at y 18..162, silently cutting off the rear
 * 29% of every bus on the map.
 */

export type VehicleIconRole = 'casing' | 'ring' | 'body';
export type VehicleIconShape = 'rail_head' | 'rail_car' | 'bus' | 'puck';

/** Outline growth, in atlas units, of each silhouette over the plain body. */
const RING_STROKE = 6;
export const CASING_STROKE = 13;

export const ICON_ROLES: readonly VehicleIconRole[] = ['casing', 'ring', 'body'];

const STROKE_FOR_ROLE: Record<VehicleIconRole, number> = {
	casing: CASING_STROKE,
	ring: RING_STROKE,
	body: 0
};

export interface ShapeDef {
	/** Cell size. Must be large enough to contain the *casing* silhouette. */
	width: number;
	height: number;
	/** Base (body) outline, authored pointing north within the cell. */
	path: string;
}

/**
 * Cell aspect ratio matters: deck.gl scales an icon so its *height* equals
 * `getSize`, with width following the cell's aspect. With `sizeUnits: 'meters'`
 * and `getSize` = vehicle length, cellWidth/cellHeight is therefore the
 * vehicle's real width-to-length ratio. A subway car is ~3.0m x 18.3m and a bus
 * ~2.6m x 12m, which is what the numbers below are tuned to once the casing is
 * included.
 */
export const SHAPES: Record<VehicleIconShape, ShapeDef> = {
	// Lead car: rounded nose, rounded tail. Same corner language as rail_car —
	// the old head car used `rx` on a <path>, which is a no-op, so it had hard
	// corners while the trailing cars were rounded.
	rail_head: {
		width: 48,
		height: 188,
		path: [
			'M 11 46',
			'Q 11 30 24 16',
			'Q 37 30 37 46',
			'L 37 164',
			'Q 37 172 29 172',
			'L 19 172',
			'Q 11 172 11 164',
			'Z'
		].join(' ')
	},
	// Trailing car: plain rounded rect. Body spans 83% of the cell so adjacent
	// cars in a consist leave a visible seam instead of merging into one bar.
	rail_car: {
		width: 48,
		height: 188,
		path: 'M 19 16 L 29 16 Q 37 16 37 24 L 37 164 Q 37 172 29 172 L 19 172 Q 11 172 11 164 L 11 24 Q 11 16 19 16 Z'
	},
	// Bus: rounded rect with a gently tapered front.
	bus: {
		width: 44,
		height: 128,
		path: [
			'M 11 26',
			'Q 11 16 22 12',
			'Q 33 16 33 26',
			'L 33 108',
			'Q 33 116 26 116',
			'L 18 116',
			'Q 11 116 11 108',
			'Z'
		].join(' ')
	},
	// Constant-screen-size marker used wherever the true-scale form would be
	// smaller than it: a round body with a directional nose. Reads cleanly at
	// ~22px and, crucially, does not pile up when a consist is sub-pixel.
	puck: {
		width: 48,
		height: 60,
		path: 'M 24 8 L 32.4 24 A 13 13 0 1 1 15.6 24 Z'
	}
};

export type VehicleIconName = `${VehicleIconShape}_${VehicleIconRole}`;

interface IconMappingEntry {
	x: number;
	y: number;
	width: number;
	height: number;
	anchorX: number;
	anchorY: number;
	mask: boolean;
}

function buildAtlas() {
	const mapping = {} as Record<VehicleIconName, IconMappingEntry>;
	const cells: string[] = [];

	let atlasWidth = 0;
	let y = 0;

	for (const shape of Object.keys(SHAPES) as VehicleIconShape[]) {
		const { width, height, path } = SHAPES[shape];

		ICON_ROLES.forEach((role, column) => {
			const x = column * width;
			mapping[`${shape}_${role}`] = {
				x,
				y,
				width,
				height,
				anchorX: width / 2,
				anchorY: height / 2,
				mask: true
			};

			const stroke = STROKE_FOR_ROLE[role];
			const strokeAttrs =
				stroke > 0
					? ` stroke="#fff" stroke-width="${stroke}" stroke-linejoin="round" stroke-linecap="round"`
					: '';
			cells.push(
				`<g transform="translate(${x} ${y})"><path d="${path}" fill="#fff"${strokeAttrs}/></g>`
			);
		});

		atlasWidth = Math.max(atlasWidth, ICON_ROLES.length * width);
		y += height;
	}

	const atlasHeight = y;
	const svg =
		`<svg xmlns="http://www.w3.org/2000/svg" width="${atlasWidth}" height="${atlasHeight}" ` +
		`viewBox="0 0 ${atlasWidth} ${atlasHeight}">${cells.join('')}</svg>`;

	return {
		mapping,
		url: `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`
	};
}

const atlas = buildAtlas();

export const VEHICLE_ICON_MAPPING = atlas.mapping;
export const VEHICLE_ICON_ATLAS = atlas.url;

/** Maps a backend `icon_key` onto an atlas shape. */
export function shapeForIconKey(iconKey: string): VehicleIconShape {
	switch (iconKey) {
		case 'rail_head':
			return 'rail_head';
		case 'rail_car':
			return 'rail_car';
		default:
			return 'bus';
	}
}
