services:
  traefik:
    image: traefik:v3.6@sha256:5ae9c349154d5298a5d61a7b25e5f3a9f53314f1515e87632120b95051c7917c
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      # port matches the martin style urls
      - 5173:80
      - 8080:8080
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:Z

  ts-frontend:
    build: frontend
    environment:
      - HOST=0.0.0.0
      - PORT=3000
      - ORIGIN=http://traefik
    depends_on:
      ts-backend:
        condition: service_started
      martin:
        condition: service_started
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend.rule=PathPrefix(`/`)
      - traefik.http.routers.frontend.entrypoints=web
      - traefik.http.routers.frontend.priority=1
      - traefik.http.services.frontend.loadbalancer.server.port=3000

  # TODO: fix valhalla returning no suitable edges error for all routes
  ts-backend:
    build: backend
    environment:
      - DATABASE_URL=postgres://trains:trains@postgis:5432/trains
      - REDIS_URL=redis://valkey:6379
      - ADDRESS=0.0.0.0:3055
    env_file:
      - .env.docker
    depends_on:
      postgis:
        condition: service_healthy
      geo-data:
        condition: service_completed_successfully
    volumes:
      - trainstatus-geo-data-test:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend.rule=PathPrefix(`/api`)
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.routers.backend.priority=100
      - traefik.http.services.backend.loadbalancer.server.port=3055

  geo-data:
    image: ghcr.io/jonerrr/trainstatus-geo-data:latest@sha256:9ea919fa20cb03d3b37ffe466a9aecafccaf3d2683a5e2ae52d61cdf78fc6066
    pull_policy: always
    restart: "no"
    volumes:
      - trainstatus-geo-data-test:/shared-data
    command:
      - /bin/sh
      - -ec
      - |
        cp -a /valhalla.json /valhalla_tiles.tar /basemap.mbtiles /shared-data/

  postgis:
    container_name: postgis
    image: docker.io/postgis/postgis:18-3.6-alpine@sha256:dcf34bd8039aa4426eb5169c03867b82988e893e38809b3134fc2e405792c8c5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=trains
      - POSTGRES_PASSWORD=trains
      - POSTGRES_DB=trains
    volumes:
      - trainstatus-db-test:/var/lib/postgresql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:Z,ro
    shm_size: 1g
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "trains", "-d", "trains"]
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    container_name: valkey
    image: valkey/valkey:alpine@sha256:e1095c6c76ee982cb2d1e07edbb7fb2a53606630a1d810d5a47c9f646b708bf5
    ports:
      - 6379:6379
    volumes:
      - trainstatus-cache-test:/data

  martin:
    container_name: martin
    image: ghcr.io/maplibre/martin:latest@sha256:13416ff1ec035af655e80b2d1889cf8ac234a013fde1308bb63c93d31b5db7a4
    environment:
      - DATABASE_URL=postgresql://trains:trains@postgis:5432/trains
    depends_on:
      postgis:
        condition: service_healthy
    command: ["--config", "/config/martin.yml"]
    labels:
      - traefik.enable=true
      - traefik.http.routers.martin.rule=PathPrefix(`/martin`)
      - traefik.http.routers.martin.entrypoints=web
      - traefik.http.routers.martin.priority=90
      - traefik.http.services.martin.loadbalancer.server.port=3000
    volumes:
      - ./geo/martin.yml:/config/martin.yml:Z,ro
      # TODO: get assets from geo-assets container for testing instead of mounting directly
      - ./geo/sprites:/assets/sprites:Z,ro
      - ./geo/styles:/assets/styles:Z,ro
      - ./geo/fonts:/assets/fonts:Z,ro
      # TODO: get basemap from geo-data container for testing
      # - ./geo/data/basemap.mbtiles:/data/basemap.mbtiles:Z,ro
      - ./geo/data/basemap.mbtiles:/data/basemap.mbtiles:Z,ro

volumes:
  trainstatus-db-test:
  trainstatus-cache-test:
  trainstatus-geo-data-test:
