# this is broken (and outdated) bc frontend can't access backend
services:
  traefik:
    image: traefik:v3.6@sha256:acfc80650104f0194a15f73dc1648f517561bc1645391a15705332a064cfc33c
    container_name: traefik
    command: --api.insecure=true --providers.docker
    ports:
      - "8000:80" # HTTP
      - "8080:8080" # Traefik Dashboard
    volumes:
      - /run/user/1000/podman/podman.sock:/var/run/docker.sock:z
    networks:
      - trainstatus-network

  backend:
    restart: unless-stopped
    image: ghcr.io/jonerrr/trainstatus-backend:staging@sha256:81222406b72549a428a4daee2e627047946602b1956e8bed092a5ba1abda4618
    container_name: backend
    environment:
      - REDIS_URL=redis://valkey:6379
      - DATABASE_URL=postgres://trains:trains@postgres:5432/trains
      - ADDRESS=0.0.0.0:3055
      - API_KEY=bustime_api_key
    depends_on:
      - postgres
      - valkey
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.services.backend.loadbalancer.server.port=3055"
      - "traefik.http.routers.backend.middlewares=strip-api-prefix"
      - "traefik.http.middlewares.strip-api-prefix.stripprefix.prefixes=/api"

  frontend:
    restart: unless-stopped
    image: ghcr.io/jonerrr/trainstatus-frontend:staging@sha256:e33477e29c8c10ff660ccbedbc6b0f56d3d4a93909d04bdb6808287ad01638c3
    container_name: frontend
    networks:
      - trainstatus-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`localhost`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"

  postgres:
    image: postgres:alpine@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911
    restart: unless-stopped
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=trains
      - POSTGRES_PASSWORD=trains
      - POSTGRES_DB=trains
    volumes:
      - postgres-trainstatus:/var/lib/postgresql/data:z
    networks:
      - trainstatus-network

  valkey:
    image: valkey/valkey:alpine@sha256:84c96f47ebe197e635cd3ddbe3ab74e8bdf783cf3befbfb1c36387275c1cd5d5
    container_name: valkey
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - trainstatus-network

volumes:
  postgres-trainstatus:

networks:
  trainstatus-network:
    driver: bridge
