services:
  postgis:
    container_name: postgis
    image: docker.io/postgis/postgis:18-3.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=trains
      - POSTGRES_PASSWORD=trains
      - POSTGRES_DB=trains
    volumes:
      - trainstatus-db:/var/lib/postgresql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:Z,ro
    shm_size: 1g
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "trains", "-d", "trains"]
      interval: 5s
      timeout: 5s
      retries: 5

  valkey:
    container_name: valkey
    image: valkey/valkey:alpine@sha256:e1095c6c76ee982cb2d1e07edbb7fb2a53606630a1d810d5a47c9f646b708bf5
    ports:
      - 6379:6379
    volumes:
      - trainstatus-cache:/data

  martin:
    container_name: martin
    image: ghcr.io/maplibre/martin:latest@sha256:9fb167869c47828254332dfe4355c1454a53f19d32d1878db54f8cbdac84c45e
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://trains:trains@postgis:5432/trains
    depends_on:
      postgis:
        condition: service_healthy
    command: ["--config", "/config/martin.yml"]
    # TODO: maybe copy data from geo-assets container instead of mounting directly.
    volumes:
      - ./geo/martin.yml:/config/martin.yml:Z,ro
      - ./geo/sprites:/assets/sprites:Z,ro
      - ./geo/styles:/assets/styles:Z,ro
      - ./geo/fonts:/assets/fonts:Z,ro
      - ./geo/data/basemap.mbtiles:/data/basemap.mbtiles:Z,ro
      # - ./geo/data/basemap.pmtiles:/data/basemap.pmtiles:Z,ro

  # maputnik:
  #   image: ghcr.io/maplibre/maputnik:main@sha256:f7726a12133e82a7583b6743f395cdf61755885158b398f8226a607ec582bab8
  #   ports:
  #     - "8888:8000"

volumes:
  trainstatus-db:
  trainstatus-cache:
