experimental_monorepo_root = true

[tools]
"github:protomaps/go-pmtiles" = "latest"

[monorepo]
config_roots = ["science", "backend", "frontend"]

[env]
DATABASE_URL = "postgres://trains:trains@localhost:5432/trains"
REDIS_URL = "redis://localhost:6379"

[tasks.dev]
depends = ["//backend:dev", "//frontend:dev"]

[tasks.basemap]
# TODO: test and improve script (e.g. get latest URL from api)
dir = "pmtiles"
run = "pmtiles extract https://build.protomaps.com/20260305.pmtiles ny.pmtiles --bbox=-74.685881,40.231692,-73.30382,41.16561"
