packages:
  - frontend
  - client

catalog:
  '@fontsource/inter': ^5.2.8
  '@hey-api/openapi-ts': 0.89.0
  '@lucide/svelte': ^0.563.1
  '@sveltejs/adapter-auto': ^7.0.0
  '@sveltejs/adapter-node': ^5.5.2
  '@sveltejs/kit': ^2.50.2
  '@sveltejs/vite-plugin-svelte': 6.2.4
  '@tailwindcss/forms': ^0.5.11
  '@tailwindcss/vite': ^4.1.18
  '@trivago/prettier-plugin-sort-imports': ^6.0.2
  '@types/d3-scale': ^4.0.9
  '@types/d3-shape': ^3.1.8
  '@types/d3-time': ^3.0.4
  '@types/eslint': ^9.6.1
  '@types/node': ^25.2.0
  d3-scale: ^4.0.2
  d3-shape: ^3.2.0
  d3-time: ^3.1.0
  dayjs: ^1.11.19
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-svelte: ^3.14.0
  flexsearch: ^0.8.212
  globals: ^17.3.0
  layercake: ^10.0.2
  prettier: ^3.8.1
  prettier-plugin-svelte: ^3.4.1
  prettier-plugin-tailwindcss: ^0.7.2
  runed: ^0.37.1
  svelte: 5.49.1
  svelte-check: ^4.3.6
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  typescript-eslint: ^8.54.0
  valibot: ^1.2.0
  vite: ^7.3.1

catalogMode: strict

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
