packages:
  - frontend
  - client

catalog:
  '@fontsource/inter': ^5.2.8
  '@hey-api/openapi-ts': 0.94.4
  '@lucide/svelte': ^0.577.0
  '@sveltejs/adapter-auto': ^7.0.1
  '@sveltejs/adapter-node': ^5.5.4
  '@sveltejs/kit': ^2.55.0
  '@sveltejs/vite-plugin-svelte': 7.0.0
  '@tailwindcss/forms': ^0.5.11
  '@tailwindcss/vite': ^4.2.2
  '@trivago/prettier-plugin-sort-imports': ^6.0.2
  '@types/d3-scale': ^4.0.9
  '@types/d3-shape': ^3.1.8
  '@types/d3-time': ^3.0.4
  '@types/eslint': ^9.6.1
  '@types/node': ^25.5.0
  '@vitest/browser-playwright': ^4.1.0
  d3-scale: ^4.0.2
  d3-shape: ^3.2.0
  d3-time: ^3.1.0
  dayjs: ^1.11.20
  eslint: ^10.1.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-svelte: ^3.15.2
  flexsearch: ^0.8.212
  globals: ^17.4.0
  layercake: ^10.0.2
  maplibre-gl: ^5.21.0
  playwright: ^1.58.2
  prettier: ^3.8.1
  prettier-plugin-svelte: ^3.5.1
  prettier-plugin-tailwindcss: ^0.7.2
  runed: ^0.37.1
  svelte: 5.54.0
  svelte-check: ^4.4.5
  svelte-maplibre-gl: ^1.0.3
  tailwindcss: ^4.2.2
  typescript: ^5.9.3
  typescript-eslint: ^8.57.1
  vite: ^8.0.1
  vitest: ^4.1.0
  vitest-browser-svelte: ^2.1.0

catalogMode: strict

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - esbuild
