fn main() {
    let mut config = prost_build::Config::new();

    // add derives for autogenerated structs that are used in API responses
    config.type_attribute(
        "transit_realtime.VehiclePosition.OccupancyStatus",
        "#[derive(serde::Serialize, serde::Deserialize, utoipa::ToSchema)]",
    );

    // you can also blanket-derive serde for everything with `.` when needed:
    // config.type_attribute(
    //     ".",
    //     "#[derive(serde::Serialize, serde::Deserialize)]",
    // );

    config
        .compile_protos(&["src/protos/gtfs-realtime.proto"], &["src/protos"])
        .unwrap();
}
