services:
  trainstatus-postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=trains
      - POSTGRES_PASSWORD=trains
      - POSTGRES_DB=trains
    volumes:
      - trainstatus-db:/var/lib/postgresql/data:z
  ts-backend:
    environment:
      - DATABASE_URL=postgres://trains:trains@trainstatus-postgres:5432/trains
      - ADDRESS=0.0.0.0:3055
      - API_KEY=bus api key
    build: .
    ports:
      - 3055:3055

volumes:
  trainstatus-db:
