services:
  postgis:
    container_name: postgis
    image: postgis/postgis:17-3.6-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=trains
      - POSTGRES_PASSWORD=trains
      - POSTGRES_DB=trains
    volumes:
      - trainstatus-db:/var/lib/postgresql/data:z
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:z,ro
    shm_size: 1g

  valkey:
    container_name: valkey
    image: valkey/valkey:alpine
    ports:
      - 6379:6379

  martin:
    container_name: martin
    image: ghcr.io/maplibre/martin:latest
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://trains:trains@postgis:5432/trains
    depends_on:
      - postgis
    command: ["--config", "/config/martin.yml"]
    volumes:
      - ./martin.yml:/config/martin.yml:z,ro
      - ./sprites:/sprites:z,ro

  # ts-backend:
  #   environment:
  #     - DATABASE_URL=postgres://trains:trains@trainstatus-postgres:5432/trains
  #     - REDIS_URL=redis://valkey:6379
  #     - ADDRESS=0.0.0.0:3055
  #     - API_KEY=bus api key
  #   build: .
  #   ports:
  #     - 3055:3055

volumes:
  trainstatus-db:
