# [tasks.start-containers]
# run = "podman compose up -d"

[tasks.csp]
run = "cargo sqlx prepare"

[tasks.migrate]
run = "sqlx migrate run"

[tasks.dev]
depends = ["//backend:migrate"]
run = "cargo run"

[tasks.build]
run = "podman build -f Dockerfile -t ghcr.io/jonerrr/trainstatus-backend ."

[tasks.test]
env = { SQLX_OFFLINE = "true", DATABASE_URL = "postgres://trains:trains@localhost:5432/trains" }
run = "cargo test"

[tasks.reset-db]
confirm = "Are you sure?"
run = """
podman kube down ../dev.pod.yml --force
podman kube play --replace ../dev.pod.yml
echo "Run DB migrations after the database is ready."
"""
# TODO: make kube play block until the db is ready, then run the migration automatically.
# depends_post = ["//backend:migrate"]

[env]
VALHALLA_CONFIG = "../geo/data/valhalla.json"
# RUST_LOG = "backend=debug"
