CREATE SCHEMA IF NOT EXISTS static;
CREATE SCHEMA IF NOT EXISTS realtime;

CREATE TABLE IF NOT EXISTS static.last_update (
    id SERIAL PRIMARY KEY,
    update_at TIMESTAMP WITH TIME ZONE NOT NULL
);