// This file is auto-generated by @hey-api/openapi-ts

export type { AlertsHandlerData, AlertsHandlerResponse, AlertsHandlerResponses, ApiAlert, ApiAlertEntity, Borough, BusDirection, ClientOptions, Route, RoutesHandlerData, RoutesHandlerResponse, RoutesHandlerResponses, RouteStop, RouteStopData, RouteType, Stop, StopData, StopsHandlerData, StopsHandlerResponse, StopsHandlerResponses, StopTime, StopTimeData, StopTimesHandlerData, StopTimesHandlerResponse, StopTimesHandlerResponses, StopType, Trip, TripsHandlerData, TripsHandlerResponse, TripsHandlerResponses } from './types.gen';
