// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

export type ApiAlert = {
    /**
     * Alert type, if planned it will start with "Planned"
     */
    alert_type: string;
    created_at: string;
    /**
     * Alert description in HTML format
     */
    description_html?: string | null;
    /**
     * End time of alert. If null, there is no end time yet.
     */
    end_time?: string | null;
    /**
     * Entities affected by alert
     */
    entities: Array<ApiAlertEntity>;
    /**
     * Alert header in HTML format
     */
    header_html: string;
    id: string;
    /**
     * Start time of alert
     */
    start_time: string;
    updated_at: string;
};

export type ApiAlertEntity = {
    /**
     * Affected route ID
     */
    route_id: string;
    /**
     * The priority of the alert for the entity in ascending order
     */
    sort_order: number;
    /**
     * Affected stop ID
     */
    stop_id?: string | null;
};

export type Borough = 'Brooklyn' | 'Queens' | 'Bronx' | 'StatenIsland' | 'Manhattan';

export type BusDirection = 'sw' | 's' | 'se' | 'e' | 'w' | 'ne' | 'nw' | 'n' | 'unknown';

export type Route = {
    color: string;
    id: string;
    long_name: string;
    route_type: RouteType;
    short_name: string;
    /**
     * This is currently only used for bus routes. It will be false for all trains.
     */
    shuttle: boolean;
};

export type RouteStop = {
    data: RouteStopData;
    route_id: string;
    stop_id: number;
    stop_sequence: number;
};

export type RouteStopData = {
    data: {
        stop_type: StopType;
    };
    type: 'Train';
} | {
    data: {
        direction: number;
        headsign: string;
    };
    type: 'Bus';
};

export type RouteType = 'train' | 'bus';

export type Stop = {
    data: StopData;
    geom: {
        x: number;
        y: number;
    };
    /**
     * Stop IDs come from the MTA's API, but (GTFS) train stop IDs are converted to numbers using their unicode values
     */
    id: number;
    name: string;
    routes: Array<RouteStop>;
    /**
     * List of stop IDs that are transfers. Currently only for train stops
     */
    transfers: Array<number>;
};

/**
 * Stop data changes based on the `route_type`
 */
export type StopData = {
    data: {
        ada: boolean;
        borough: Borough;
        north_headsign: string;
        /**
         * Notes about ADA accessibility at the stop
         */
        notes?: string | null;
        south_headsign: string;
    };
    type: 'Train';
} | {
    data: {
        direction: BusDirection;
    };
    type: 'Bus';
};

export type StopTime = {
    arrival: string;
    data: StopTimeData;
    departure: string;
    stop_id: number;
    trip_id: string;
};

export type StopTimeData = {
    data: {
        actual_track?: string | null;
        scheduled_track?: string | null;
    };
    type: 'Train';
} | {
    type: 'Bus';
};

export type StopType = 'full_time' | 'part_time' | 'late_night' | 'rush_hour_one_direction' | 'rush_hour' | 'weekday_only' | 'nights_weekends_only' | 'unknown';

export type Trip = {
    /**
     * For trains, this is the start time of the trip.
     * For buses, this is the start date of the trip + the current time the trip was first seen in the feed.
     */
    created_at: string;
    /**
     * This is the deviation from the schedule in seconds.
     * It currently only applies to buses.
     * A negative value means the bus is ahead of schedule and a positive value means the bus is behind schedule.
     */
    deviation?: number | null;
    /**
     * For trains, 0 is southbound, 1 is northbound.
     * For buses, the direction is also 0 or 1, but it corresponds to the stops in the route.
     */
    direction?: number | null;
    id: string;
    /**
     * This the ID from the MTA feed
     */
    mta_id: string;
    route_id: string;
    route_type: RouteType;
    updated_at: string;
    vehicle_id: string;
};

export type AlertsHandlerData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: number;
    };
    url: '/v1/alerts';
};

export type AlertsHandlerResponses = {
    /**
     * Subway and bus alerts
     */
    200: Array<ApiAlert>;
};

export type AlertsHandlerResponse = AlertsHandlerResponses[keyof AlertsHandlerResponses];

export type RoutesHandlerData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return in GeoJSON format instead of JSON
         */
        geojson?: boolean;
        /**
         * Filter by route type. If none provided, all routes are returned.
         */
        route_type?: null | RouteType;
    };
    url: '/v1/routes';
};

export type RoutesHandlerResponses = {
    /**
     * Subway and bus routes. WARNING: W train geometry is missing.
     */
    200: Array<Route>;
};

export type RoutesHandlerResponse = RoutesHandlerResponses[keyof RoutesHandlerResponses];

export type StopTimesHandlerData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Comma-separated list of bus route IDs to include in response. Be sure to URL encode this.
         */
        bus_route_ids?: Array<string>;
        /**
         * Only return bus stop times. If `bus_route_ids` is not specified, this will return all TRAIN stop times.
         */
        only_bus?: boolean;
        /**
         * Make sure `trip.updated_at` and `stop_time.arrival` are after the current time. By default, this only checks `trip.updated_at`.
         */
        filter_arrival?: boolean;
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: number;
    };
    url: '/v1/stop_times';
};

export type StopTimesHandlerResponses = {
    /**
     * Subway and bus stop times. Unlike other routes, by default this will ONLY return train routes unless specified.
     */
    200: Array<StopTime>;
};

export type StopTimesHandlerResponse = StopTimesHandlerResponses[keyof StopTimesHandlerResponses];

export type StopsHandlerData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return in GeoJSON format instead of JSON
         */
        geojson?: boolean;
        /**
         * Filter by route type. If none provided, all routes are returned.
         */
        route_type?: null | RouteType;
    };
    url: '/v1/stops';
};

export type StopsHandlerResponses = {
    /**
     * Subway and bus stops
     */
    200: Array<Stop>;
};

export type StopsHandlerResponse = StopsHandlerResponses[keyof StopsHandlerResponses];

export type TripsHandlerData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Return in GeoJSON format instead of JSON
         */
        geojson?: boolean;
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: number;
    };
    url: '/v1/trips';
};

export type TripsHandlerResponses = {
    /**
     * Subway and bus trips
     */
    200: Array<Trip>;
};

export type TripsHandlerResponse = TripsHandlerResponses[keyof TripsHandlerResponses];
