// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * API response for alerts - flattened with all related data
 */
export type ApiAlert = {
    /**
     * Alert type, if planned it will start with "Planned"
     */
    alert_type: string;
    created_at: string;
    /**
     * Alert description in HTML format
     */
    description_html?: string | null;
    /**
     * End time of alert. If null, there is no end time yet.
     */
    end_time?: string | null;
    /**
     * Entities affected by alert
     */
    entities: Array<ApiAlertEntity>;
    /**
     * Alert header in HTML format
     */
    header_html: string;
    id: string;
    original_id: string;
    /**
     * Start time of alert (earliest active period)
     */
    start_time: string;
    updated_at: string;
};

export type ApiAlertEntity = {
    /**
     * Affected route ID
     */
    route_id: string;
    /**
     * The priority of the alert for the entity in ascending order
     */
    sort_order: number;
    /**
     * Affected stop ID
     */
    stop_id?: string | null;
};

export type Borough = 'brooklyn' | 'queens' | 'bronx' | 'staten_island' | 'manhattan';

/**
 * Direction of the stop. Currently only for bus stops
 */
export type CompassDirection = 's_w' | 's' | 's_e' | 'e' | 'w' | 'n_e' | 'n_w' | 'n' | 'unknown';

export type MtaBusData = {
    direction: CompassDirection;
};

export type MtaSubwayData = {
    ada: boolean;
    borough: Borough;
    north_headsign: string;
    /**
     * Notes about ADA accessibility at the stop
     */
    notes?: string | null;
    south_headsign: string;
};

export type Route = {
    color: string;
    data: RouteData;
    id: string;
    long_name: string;
    short_name: string;
};

/**
 * Stop data changes based on the `Source`
 */
export type RouteData = (MtaBusData & {
    source: 'mta_bus';
}) | {
    source: 'mta_subway';
};

export type RouteStop = {
    data: RouteStopData;
    route_id: string;
    stop_id: string;
    stop_sequence: number;
};

export type RouteStopData = {
    source: 'mta_subway';
    stop_type: StopType;
} | {
    /**
     * Direction of bus trips that serve this stop
     */
    direction: number;
    headsign: string;
    source: 'mta_bus';
};

export type Source = 'mta_subway' | 'mta_bus';

export type Stop = {
    data: StopData;
    geom: {
        coordinates: {
            Point: {
                x: number;
                y: number;
            };
        };
        type: 'Point';
    };
    id: string;
    name: string;
    routes: Array<RouteStop>;
    /**
     * List of stop IDs that are transfers. Currently only for train stops
     */
    transfers: Array<string>;
};

/**
 * Stop data changes based on the `Source`
 */
export type StopData = (MtaSubwayData & {
    source: 'mta_subway';
}) | (MtaBusData & {
    source: 'mta_bus';
});

export type StopTime = {
    arrival: string;
    data: StopTimeData;
    departure: string;
    stop_id: string;
    trip_id: string;
};

export type StopTimeData = {
    actual_track?: string | null;
    scheduled_track?: string | null;
    source: 'mta_subway';
} | {
    source: 'mta_bus';
};

export type StopType = 'full_time' | 'part_time' | 'late_night' | 'rush_hour_one_direction' | 'rush_hour' | 'weekday_only' | 'nights_weekends_only' | 'unknown';

export type Trip = {
    /**
     * For the MTA subway, this is the start time of the trip.
     * For the MTA buses, this is the start date of the trip + the current time the trip was first seen in the feed.
     */
    created_at: string;
    data: TripData;
    /**
     * For the MTA subway, 1 is northbound, 3 is southbound.
     * For the MTA buses, the direction is also 0 or 1, but it corresponds to the stops in the route.
     */
    direction?: number | null;
    id: string;
    /**
     * Original trip identifier from the data source
     */
    original_id: string;
    route_id: string;
    updated_at: string;
    vehicle_id: string;
};

/**
 * Trip data changes based on the `Source`
 */
export type TripData = (MtaBusData & {
    source: 'mta_bus';
}) | {
    source: 'mta_subway';
};

export type AlertsHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: {
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: number;
    };
    url: '/v1/alerts/{source}';
};

export type AlertsHandlerResponses = {
    /**
     * Alerts for the specified source
     */
    200: Array<ApiAlert>;
};

export type AlertsHandlerResponse = AlertsHandlerResponses[keyof AlertsHandlerResponses];

export type RoutesHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: never;
    url: '/v1/routes/{source}';
};

export type RoutesHandlerResponses = {
    /**
     * Subway and bus routes. WARNING: W train geometry is missing.
     */
    200: Array<Route>;
};

export type RoutesHandlerResponse = RoutesHandlerResponses[keyof RoutesHandlerResponses];

export type StopTimesHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: {
        /**
         * Comma-separated list of route IDs to filter by. Be sure to URL encode this.
         */
        route_ids?: Array<string>;
        /**
         * Make sure `trip.updated_at` and `stop_time.arrival` are after the current time. By default, this only checks `trip.updated_at`.
         */
        filter_arrival?: boolean;
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: number;
    };
    url: '/v1/stop_times/{source}';
};

export type StopTimesHandlerResponses = {
    /**
     * Stop times for the specified source
     */
    200: Array<StopTime>;
};

export type StopTimesHandlerResponse = StopTimesHandlerResponses[keyof StopTimesHandlerResponses];

export type StopsHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: never;
    url: '/v1/stops/{source}';
};

export type StopsHandlerResponses = {
    /**
     * Source stops
     */
    200: Array<Stop>;
};

export type StopsHandlerResponse = StopsHandlerResponses[keyof StopsHandlerResponses];

export type TripsHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: {
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: number;
    };
    url: '/v1/trips/{source}';
};

export type TripsHandlerResponses = {
    /**
     * Trips for the specified source
     */
    200: Array<Trip>;
};

export type TripsHandlerResponse = TripsHandlerResponses[keyof TripsHandlerResponses];
