// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}/api` | (string & {});
};

/**
 * API response for alerts - flattened with all related data
 */
export type ApiAlert = {
    /**
     * Alert type, if planned it will start with "Planned"
     */
    alert_type: string;
    created_at: Date;
    /**
     * Alert description in HTML format
     */
    description_html?: string | null;
    /**
     * End time of alert. If null, there is no end time yet.
     */
    end_time?: Date | null;
    /**
     * Entities affected by alert
     */
    entities: Array<ApiAlertEntity>;
    /**
     * Alert header in HTML format
     */
    header_html: string;
    id: string;
    original_id: string;
    /**
     * Start time of alert (earliest active period)
     */
    start_time: Date;
    updated_at: Date;
};

export type ApiAlertEntity = {
    /**
     * Affected route ID
     */
    route_id: string;
    /**
     * The priority of the alert for the entity in ascending order
     */
    sort_order: number;
    /**
     * Affected stop ID
     */
    stop_id?: string | null;
};

export type Borough = 'brooklyn' | 'queens' | 'bronx' | 'staten_island' | 'manhattan';

/**
 * Direction of the stop. Currently only for bus stops
 */
export type CompassDirection = 's_w' | 's' | 's_e' | 'e' | 'w' | 'n_e' | 'n_w' | 'n' | 'unknown';

export type MtaBusData = {
    /**
     * Deviation from the schedule in seconds.
     * A negative value means the bus is ahead of schedule and a positive value means the bus is behind schedule.
     */
    deviation?: number | null;
};

export type MtaBusPositionData = {
    bearing: number;
    capacity?: number | null;
    passengers?: number | null;
    phase?: string | null;
    status?: string | null;
};

export type MtaBusStopData = {
    direction: CompassDirection;
};

export type MtaSubwayPositionData = {
    assigned: boolean;
    status?: string | null;
};

export type MtaSubwayStopData = {
    ada: boolean;
    borough: Borough;
    north_headsign: string;
    /**
     * Notes about ADA accessibility at the stop
     */
    notes?: string | null;
    south_headsign: string;
};

export type MtaSubwayStopTimeData = {
    actual_track?: string | null;
    scheduled_track?: string | null;
};

export type PositionData = (MtaSubwayPositionData & {
    source: 'mta_subway';
}) | (MtaBusPositionData & {
    source: 'mta_bus';
});

export type Route = {
    color: string;
    data: RouteData;
    id: string;
    long_name: string;
    short_name: string;
};

/**
 * Stop data changes based on the `Source`
 */
export type RouteData = (MtaBusData & {
    source: 'mta_bus';
}) | {
    source: 'mta_subway';
};

export type RouteStop = {
    data: RouteStopData;
    route_id: string;
    stop_id: string;
    stop_sequence: number;
};

export type RouteStopData = {
    source: 'mta_subway';
    stop_type: StopType;
} | {
    /**
     * Direction of bus trips that serve this stop
     */
    direction: number;
    headsign: string;
    source: 'mta_bus';
};

export type Source = 'mta_subway' | 'mta_bus';

export type Stop = {
    data: StopData;
    geom: {
        Point: {
            x: number;
            y: number;
        };
    };
    id: string;
    name: string;
    routes: Array<RouteStop>;
    transfers: Array<Transfer>;
};

/**
 * Stop data changes based on the `Source`
 */
export type StopData = (MtaSubwayStopData & {
    source: 'mta_subway';
}) | (MtaBusStopData & {
    source: 'mta_bus';
});

export type StopTime = {
    arrival: Date;
    data: StopTimeData;
    departure: Date;
    stop_id: string;
    trip_id: string;
};

export type StopTimeData = (MtaSubwayStopTimeData & {
    source: 'mta_subway';
}) | {
    source: 'mta_bus';
};

export type StopType = 'full_time' | 'part_time' | 'late_night' | 'rush_hour_one_direction' | 'rush_hour' | 'weekday_only' | 'nights_weekends_only' | 'unknown';

export type Transfer = {
    min_transfer_time?: number | null;
    to_stop_id: string;
    to_stop_source: Source;
    /**
     * Numbers between 0-5 represent the GTFS-defined transfer types: https://gtfs.org/documentation/schedule/reference/#transferstxt
     * 6 are transfers that we calculated based on proximity.
     */
    transfer_type: number;
};

export type Trip = {
    /**
     * For the MTA subway, this is the start time of the trip.
     * For the MTA buses, this is the start date of the trip + the current time the trip was first seen in the feed.
     */
    created_at: Date;
    data: TripData;
    /**
     * For the MTA subway, 1 is northbound, 3 is southbound.
     * For the MTA buses, the direction is 0 or 1, but it corresponds to which stops the bus serves, not cardinality. You can determine this by looking at the `RouteStop` data for the stops the trip serves.
     */
    direction: number;
    id: string;
    /**
     * Original trip identifier from the data source
     */
    original_id: string;
    route_id: string;
    updated_at: Date;
    vehicle_id: string;
};

/**
 * Trip data changes based on the `Source`
 */
export type TripData = (MtaBusData & {
    source: 'mta_bus';
}) | {
    source: 'mta_subway';
};

/**
 * Current vehicle position (for upsert into vehicle_position table)
 */
export type VehiclePosition = {
    data: PositionData;
    geom?: {
        Point: {
            x: number;
            y: number;
        };
    };
    stop_id?: string | null;
    trip_id?: string | null;
    updated_at: Date;
    vehicle_id: string;
};

export type AlertsHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: {
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: bigint;
    };
    url: '/v1/alerts/{source}';
};

export type AlertsHandlerResponses = {
    /**
     * Alerts for the specified source
     */
    200: Array<ApiAlert>;
};

export type AlertsHandlerResponse = AlertsHandlerResponses[keyof AlertsHandlerResponses];

export type PositionsHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: {
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: bigint;
    };
    url: '/v1/positions/{source}';
};

export type PositionsHandlerResponses = {
    /**
     * Vehicle positions for the specified source
     */
    200: Array<VehiclePosition>;
};

export type PositionsHandlerResponse = PositionsHandlerResponses[keyof PositionsHandlerResponses];

export type RoutesHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: never;
    url: '/v1/routes/{source}';
};

export type RoutesHandlerResponses = {
    /**
     * Subway and bus routes. WARNING: W train geometry is missing.
     */
    200: Array<Route>;
};

export type RoutesHandlerResponse = RoutesHandlerResponses[keyof RoutesHandlerResponses];

export type StopTimesHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: {
        /**
         * Comma-separated list of route IDs to filter by. Be sure to URL encode this.
         */
        route_ids?: Array<string>;
        /**
         * Make sure `trip.updated_at` and `stop_time.arrival` are after the current time. By default, this only checks `trip.updated_at`.
         */
        filter_arrival?: boolean;
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: bigint;
    };
    url: '/v1/stop_times/{source}';
};

export type StopTimesHandlerResponses = {
    /**
     * Stop times for the specified source
     */
    200: Array<StopTime>;
};

export type StopTimesHandlerResponse = StopTimesHandlerResponses[keyof StopTimesHandlerResponses];

export type StopsHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: never;
    url: '/v1/stops/{source}';
};

export type StopsHandlerResponses = {
    /**
     * Source stops
     */
    200: Array<Stop>;
};

export type StopsHandlerResponse = StopsHandlerResponses[keyof StopsHandlerResponses];

export type TripsHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: {
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: bigint;
    };
    url: '/v1/trips/{source}';
};

export type TripsHandlerResponses = {
    /**
     * Trips for the specified source
     */
    200: Array<Trip>;
};

export type TripsHandlerResponse = TripsHandlerResponses[keyof TripsHandlerResponses];
