// This file is auto-generated by @hey-api/openapi-ts

import type { AlertsHandlerResponse, PositionsHandlerResponse, StopTimesHandlerResponse, TripsHandlerResponse } from './types.gen';

const apiAlertSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    if (data.end_time) {
        data.end_time = new Date(data.end_time);
    }
    data.start_time = new Date(data.start_time);
    data.updated_at = new Date(data.updated_at);
    return data;
};

export const alertsHandlerResponseTransformer = async (data: any): Promise<AlertsHandlerResponse> => {
    data = data.map((item: any) => apiAlertSchemaResponseTransformer(item));
    return data;
};

const vehiclePositionSchemaResponseTransformer = (data: any) => {
    data.updated_at = new Date(data.updated_at);
    return data;
};

export const positionsHandlerResponseTransformer = async (data: any): Promise<PositionsHandlerResponse> => {
    data = data.map((item: any) => vehiclePositionSchemaResponseTransformer(item));
    return data;
};

const stopTimeSchemaResponseTransformer = (data: any) => {
    data.arrival = new Date(data.arrival);
    data.departure = new Date(data.departure);
    return data;
};

export const stopTimesHandlerResponseTransformer = async (data: any): Promise<StopTimesHandlerResponse> => {
    data = data.map((item: any) => stopTimeSchemaResponseTransformer(item));
    return data;
};

const tripSchemaResponseTransformer = (data: any) => {
    data.created_at = new Date(data.created_at);
    data.updated_at = new Date(data.updated_at);
    return data;
};

export const tripsHandlerResponseTransformer = async (data: any): Promise<TripsHandlerResponse> => {
    data = data.map((item: any) => tripSchemaResponseTransformer(item));
    return data;
};
