// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:5173' | (string & {});
};

export type AlertData = (MtaAlertData & {
    source: 'mta_subway';
}) | (MtaAlertData & {
    source: 'mta_bus';
}) | {
    source: 'njt_bus';
};

export type AlertFormat = 'plain' | 'html';

export type AlertSection = 'header' | 'description';

/**
 * API response for alerts - flattened with all related data
 */
export type ApiAlert = {
    created_at: Date;
    data: AlertData;
    /**
     * End time of alert. If null, there is no end time yet.
     */
    end_time?: Date | null;
    /**
     * Entities affected by alert
     */
    entities: Array<ApiAlertEntity>;
    id: string;
    original_id: string;
    /**
     * Start time of alert (earliest active period)
     */
    start_time: Date;
    translations: Array<ApiAlertTranslation>;
    updated_at: Date;
};

export type ApiAlertEntity = {
    /**
     * Affected route ID
     */
    route_id: string;
    /**
     * The priority of the alert for the entity in ascending order
     */
    sort_order: number;
    /**
     * Affected stop ID
     */
    stop_id?: string | null;
};

/**
 * Alert translations for API response (it just doesn't have the alert_id since it's nested under the alert)
 */
export type ApiAlertTranslation = {
    format: AlertFormat;
    language: string;
    section: AlertSection;
    text: string;
};

export type Borough = 'brooklyn' | 'queens' | 'bronx' | 'staten_island' | 'manhattan';

/**
 * Represents a marker on the platform that indicates where a consist will stop.
 * For example if we have "marked_as: "S", direction: North, position_ft: 13",
 * That means this marker is for northbound trains which will arrive from the south and stop 13 feet from the north end of the platform.
 */
export type CarMarker = {
    /**
     * Length of the consist in feet that this marker is meant to accommodate
     */
    consist_length_ft?: number | null;
    /**
     * Direction of the trips that the marker is for.
     */
    direction: PlatformDirection;
    /**
     * One-person operations
     */
    is_opto: boolean;
    /**
     * The label on the platform. Usually is a number representing the amount of cars in the consist.
     * Sometimes its "S" or "OPTO S", which seems to be short for the motorman's stop board.
     */
    marked_as: string;
    /**
     * Position of the marker on the platform in feet starting from the railway north end of the platform
     * The value can be between 0 and the length of the platform edge.
     */
    position_ft: number;
};

/**
 * Direction a bus travels through the stop, bucketed into eight compass sectors.
 * Currently only for bus stops.
 */
export type CompassDirection = 'sw' | 's' | 'se' | 'e' | 'w' | 'ne' | 'nw' | 'n' | 'unknown';

export type Consist = {
    car_count: number;
    car_length_feet: number;
};

export type ConsistCar = {
    number: string;
    type?: string | null;
};

export type EgressPoint = {
    egress_type: EgressType;
    id: number;
    /**
     * Position of the egress point on the platform in feet from a reference point
     */
    position_ft: number;
    vertical_direction: VerticalDirection;
};

export type EgressType = 'STAIRCASE' | 'ELEVATOR' | 'ESCALATOR' | 'FARE_CONTROL' | 'DOOR' | 'EXIT' | 'RAMP' | 'UNKNOWN';

export type MtaAlertData = {
    alert_type: string;
    /**
     * The id of the planned work this alert was cloned from
     */
    clone_id?: string | null;
    display_before_active: number;
};

export type MtaBusData = {
    /**
     * Deviation from the schedule in seconds.
     * A negative value means the bus is ahead of schedule and a positive value means the bus is behind schedule.
     */
    deviation?: number | null;
};

/**
 * One of a bus route's two terminals, as printed on the bus's headsign.
 */
export type MtaBusDirection = {
    destination: string;
    /**
     * Matches `Trip.direction` for trips on this route.
     */
    direction_id: number;
    /**
     * Intermediate streets the MTA prints under the destination, e.g. `["Av U"]`.
     */
    via?: Array<string>;
};

export type MtaBusPositionData = {
    bearing: number;
    capacity?: number | null;
    passengers?: number | null;
    phase?: string | null;
    status?: string | null;
};

export type MtaBusRouteData = {
    borough?: null | Borough;
    /**
     * Destination headsigns, ordered by `direction_id`.
     *
     * Headsigns live here rather than on `RouteStop` because the upstream feed
     * exposes no stop-to-direction mapping — a stop's route entry carries only
     * shape IDs. Consumers resolve a trip's headsign from its `direction`.
     */
    directions?: Array<MtaBusDirection>;
    name_number: number;
    /**
     * Letter prefix of the route name, e.g. `Bx` in `Bx12`. Normalized to the
     * casing used in the route name, since the upstream feed mixes `BX` and `Bx`.
     */
    name_prefix: string;
    /**
     * Variant suffix, e.g. `-SBS` in `M15-SBS` or `A` in `Bx18A`.
     */
    name_suffix?: string | null;
    service_types: Array<string>;
    /**
     * All shape IDs associated with this route (from Helium infra, via stop-route data).
     * Used at realtime to pick the best-fitting shape for a trip when GTFS-RT
     * does not provide shape_id directly.
     */
    shape_ids?: Array<string>;
    sort_key: number;
};

export type MtaBusStopData = {
    bearing?: number | null;
    direction: CompassDirection;
    is_boardable: boolean;
};

export type MtaSubwayPositionData = {
    assigned: boolean;
    status?: string | null;
};

export type MtaSubwayStopData = {
    bubble_id: string;
    gtfs_stop_id: string;
    is_major: boolean;
    line: string;
    north_headsign: string;
    platform_edges: Array<PlatformEdge>;
    south_headsign: string;
    station_group_id: string;
};

export type MtaSubwayStopTimeData = {
    actual_track?: string | null;
    platform_edges?: Array<string>;
    scheduled_track?: string | null;
};

export type MtaSubwayTripData = {
    consist?: null | Consist;
    consist_cars: Array<ConsistCar>;
};

export type NjtBusData = {
    /**
     * Deviation from the schedule in seconds.
     * A negative value means the bus is ahead of schedule and a positive value means the bus is behind schedule.
     */
    deviation?: number | null;
    headsign: string;
};

export type NjtBusPositionData = {
    occupancy_status: OccupancyStatus;
};

export type NjtBusStopData = {
    /**
     * Public-facing 5-digit stop code (e.g. "10001"), shown on signs and NJT apps
     */
    stop_code: string;
};

/**
 * The state of passenger occupancy for the vehicle or carriage.
 * Individual producers may not publish all OccupancyStatus values. Therefore,
 * consumers must not assume that the OccupancyStatus values follow a linear
 * scale. Consumers should represent OccupancyStatus values as the state
 * indicated and intended by the producer. Likewise, producers must use
 * OccupancyStatus values that correspond to actual vehicle occupancy states.
 * For describing passenger occupancy levels on a linear scale, see
 * `occupancy_percentage`. This field is still experimental, and subject to
 * change. It may be formally adopted in the future.
 */
export type OccupancyStatus = 'Empty' | 'ManySeatsAvailable' | 'FewSeatsAvailable' | 'StandingRoomOnly' | 'CrushedStandingRoomOnly' | 'Full' | 'NotAcceptingPassengers' | 'NoDataAvailable' | 'NotBoardable';

export type PlatformDirection = 'NORTH' | 'SOUTH';

export type PlatformEdge = {
    car_markers: Array<CarMarker>;
    egress_points: Array<EgressPoint>;
    id: string;
    length_ft: number;
};

export type PositionData = (MtaSubwayPositionData & {
    source: 'mta_subway';
}) | (MtaBusPositionData & {
    source: 'mta_bus';
}) | (NjtBusPositionData & {
    source: 'njt_bus';
});

export type Route = {
    color: string;
    data: RouteData;
    id: string;
    long_name: string;
    short_name: string;
    text_color: string;
};

/**
 * Stop data changes based on the `Source`
 */
export type RouteData = (MtaBusRouteData & {
    source: 'mta_bus';
}) | {
    source: 'mta_subway';
} | {
    source: 'njt_bus';
};

export type RouteStop = {
    data: RouteStopData;
    route_id: string;
    stop_id: string;
    stop_sequence: number;
};

export type RouteStopData = {
    source: 'mta_subway';
    stop_type: StopType;
} | {
    /**
     * Direction of bus trips that serve this stop
     */
    direction: number;
    headsign: string;
    /**
     * Populated by the backend based on proximity, direction, and headsign. Not guaranteed to be accurate.
     */
    opposite_stop_id?: string | null;
    /**
     * Helium shape_ids (across all service types) known to pass through this stop
     * for this route. Used to deterministically resolve which of a route's several
     * candidate shapes a realtime trip is following, by counting how many of the
     * trip's actual stops each candidate is known to serve.
     */
    shape_ids?: Array<string>;
    source: 'mta_bus';
} | {
    /**
     * 0 or 1 from GTFS direction_id
     */
    direction: number;
    headsign: string;
    /**
     * Populated by the backend based on proximity and direction. Not guaranteed to be accurate.
     */
    opposite_stop_id?: string | null;
    source: 'njt_bus';
};

export type Source = 'mta_subway' | 'mta_bus' | 'njt_bus';

export type Stop = {
    data: StopData;
    geom: {
        Point: {
            x: number;
            y: number;
        };
    };
    id: string;
    name: string;
    routes: Array<RouteStop>;
    /**
     * See https://gtfs.org/documentation/schedule/reference/#stopstxt location_type field for more details on what these values represent
     * Values above 4 are not
     */
    transfers: Array<Transfer>;
};

/**
 * Stop data changes based on the `Source`
 */
export type StopData = (MtaSubwayStopData & {
    source: 'mta_subway';
}) | (MtaBusStopData & {
    source: 'mta_bus';
}) | (NjtBusStopData & {
    source: 'njt_bus';
});

export type StopTime = {
    arrival: Date;
    data: StopTimeData;
    departure: Date;
    stop_id: string;
    trip_id: string;
};

export type StopTimeData = (MtaSubwayStopTimeData & {
    source: 'mta_subway';
}) | {
    source: 'mta_bus';
} | {
    source: 'njt_bus';
};

export type StopType = 'full_time' | 'part_time' | 'late_night' | 'rush_hour_one_direction' | 'rush_hour' | 'weekday_only' | 'nights_weekends_only' | 'unknown';

export type Transfer = {
    min_transfer_time?: number | null;
    to_stop_id: string;
    to_stop_source: Source;
    /**
     * Numbers between 0-5 represent the GTFS-defined transfer types: https://gtfs.org/documentation/schedule/reference/#transferstxt
     * 6 are transfers that we calculated based on proximity.
     */
    transfer_type: number;
};

export type Trip = {
    /**
     * For the MTA subway, this is the start time of the trip.
     * For the MTA buses, this is the start date of the trip + the current time the trip was first seen in the feed.
     */
    created_at: Date;
    data: TripData;
    /**
     * For the MTA subway, 1 is northbound, 3 is southbound.
     * For the MTA buses, the direction is 0 or 1, but it corresponds to which stops the bus serves, not cardinality. You can determine this by looking at the `RouteStop` data for the stops the trip serves.
     */
    direction: number;
    id: string;
    /**
     * Original trip identifier from the data source
     */
    original_id: string;
    route_id: string;
    shape_ids: Array<string>;
    updated_at: Date;
    vehicle_id: string;
};

/**
 * Trip data changes based on the `Source`
 */
export type TripData = (MtaBusData & {
    source: 'mta_bus';
}) | (MtaSubwayTripData & {
    source: 'mta_subway';
}) | (NjtBusData & {
    source: 'njt_bus';
});

/**
 * Current vehicle position (for upsert into vehicle_position table)
 */
export type VehiclePosition = {
    data: PositionData;
    geom?: {
        Point: {
            x: number;
            y: number;
        };
    };
    stop_id?: string | null;
    trip_id?: string | null;
    updated_at: Date;
    vehicle_id: string;
};

export type VerticalDirection = 'UP' | 'DOWN' | 'NONE';

export type AlertsHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: {
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: bigint;
    };
    url: '/api/v1/alerts/{source}';
};

export type AlertsHandlerResponses = {
    /**
     * Alerts for the specified source
     */
    200: Array<ApiAlert>;
};

export type AlertsHandlerResponse = AlertsHandlerResponses[keyof AlertsHandlerResponses];

export type PositionsHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: {
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: bigint;
    };
    url: '/api/v1/positions/{source}';
};

export type PositionsHandlerResponses = {
    /**
     * Vehicle positions for the specified source
     */
    200: Array<VehiclePosition>;
};

export type PositionsHandlerResponse = PositionsHandlerResponses[keyof PositionsHandlerResponses];

export type RoutesHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: never;
    url: '/api/v1/routes/{source}';
};

export type RoutesHandlerResponses = {
    /**
     * Subway and bus routes. WARNING: W train geometry is missing.
     */
    200: Array<Route>;
};

export type RoutesHandlerResponse = RoutesHandlerResponses[keyof RoutesHandlerResponses];

export type StopTimesHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: {
        /**
         * Comma-separated list of route IDs to filter by. Be sure to URL encode this.
         */
        route_ids?: Array<string>;
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: bigint;
    };
    url: '/api/v1/stop_times/{source}';
};

export type StopTimesHandlerResponses = {
    /**
     * Stop times for the specified source
     */
    200: Array<StopTime>;
};

export type StopTimesHandlerResponse = StopTimesHandlerResponses[keyof StopTimesHandlerResponses];

export type StopsHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: never;
    url: '/api/v1/stops/{source}';
};

export type StopsHandlerResponses = {
    /**
     * Source stops
     */
    200: Array<Stop>;
};

export type StopsHandlerResponse = StopsHandlerResponses[keyof StopsHandlerResponses];

export type TrajectoriesHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: {
        route_ids?: Array<string>;
        /**
         * Viewport bounds: min_lon,min_lat,max_lon,max_lat
         */
        bbox?: string | null;
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: bigint;
    };
    url: '/api/v1/trajectories/{source}';
};

export type TrajectoriesHandlerErrors = {
    /**
     * Invalid bbox parameter
     */
    400: unknown;
};

export type TrajectoriesHandlerResponses = {
    /**
     * Arrow IPC stream of trajectories
     */
    200: unknown;
};

export type TripsHandlerData = {
    body?: never;
    path: {
        /**
         * Data source
         */
        source: Source;
    };
    query?: {
        /**
         * Unix timestamp to use as the current time. If not specified, the current time is used.
         */
        at?: bigint;
    };
    url: '/api/v1/trips/{source}';
};

export type TripsHandlerResponses = {
    /**
     * Trips for the specified source
     */
    200: Array<Trip>;
};

export type TripsHandlerResponse = TripsHandlerResponses[keyof TripsHandlerResponses];
