# config.properties
download=true
# TODO: switch back to mlt
# tile_format=mlt
# currently broken in maplibre:
# mlt_advanced=true
# compression breaks maplibre for some reason
tile_compression=none
force=true
osm_path=/data/merged.osm.pbf
output=/data/basemap.pmtiles

tmpdir=/tmp/planetiler
natural_earth_path=/data/sources/natural_earth.zip
water_polygons_path=/data/sources/water_polygons.zip
lake_centerlines_path=/data/sources/lake_centerline.shp.zip
wikidata_cache=/data/sources/wikidata_names.json

# Excluded layers to keep the map clean (TODO: hide in style config instead)
# exclude_layers=housenumber,landcover,landuse,mountain_peak,poi,park
