download=true
tile_format=mlt
mlt_advanced=true
# i think tile_compresison causes issues with maplibre.
# But also keeping it disabled bc the mlt_advanced should already be doing a good job of keeping file sizes down
tile_compression=none
force=true
osm_path=/data/merged.osm.pbf
output=/data/basemap.mbtiles

tmpdir=/tmp/planetiler
natural_earth_path=/data/sources/natural_earth.zip
water_polygons_path=/data/sources/water_polygons.zip
lake_centerlines_path=/data/sources/lake_centerline.shp.zip
wikidata_cache=/data/sources/wikidata_names.json

# Excluded layers to keep the map clean (TODO: hide in style config instead)
# exclude_layers=housenumber,landcover,landuse,mountain_peak,poi,park
