name: Build and Push docker images

on:
  release:
    types: [published]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # TODO: fix tags (think i need to remove ghcr.io/ from the tags)
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./backend
            image: ghcr.io/${{ github.repository_owner }}/trainstatus-backend
            tags: |
              latest
              ${{ github.event.release.tag_name }}
          - context: ./frontend
            image: ghcr.io/${{ github.repository_owner }}/trainstatus-frontend
            tags: |
              latest
              ${{ github.event.release.tag_name }}

    permissions:
      contents: read
      packages: write

    steps:
      # don't think i need checkout bc build-push-action does it
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ matrix.image }}
          tags: ${{ matrix.tags }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
