name: Build and Push Docker Images to Staging

on:
  push:
    branches:
      - master

jobs:
  build-and-push-staging:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: ./backend
            image: ghcr.io/${{ github.repository_owner }}/trainstatus-backend
          - context: ./frontend
            image: ghcr.io/${{ github.repository_owner }}/trainstatus-frontend

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Metadata for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ matrix.image }}
          tags: |
            staging
            staging-${{ github.sha }}

      - name: Build and Push Docker Image to Staging
        uses: docker/build-push-action@v5.3.0
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
